### ISSUE TITLE
TypeError: currentReducer is not a function

### ISSUE THREAD

**Issue by DjebbZ** [milankinen/livereactload#101]
Sorry if this is the wrong place, I'm not sure if it's related to redux, React-redux, livereactload or the way I use all of them.

When I edit some code in my app, I keep having (at random times) the error in the title, which aborts the patching with the message `LiveReactload :: Abort patching`. I use the same code as in the [2nd example](https://github.com/milankinen/livereactload/blob/master/examples/02-redux/store/configureStore.js), since React-redux requires [explicit reloading management](https://github.com/rackt/react-redux/releases/tag/v2.0.0).

This is the complete code in my `store.js` file :

``` javascript
var redux           = require("redux");
var thunkMiddleware = require("redux-thunk");
var createLogger    = require("redux-logger");
var HSApp           = require("../reducers/index").HSApp;
var initialState    = require("../reducers/index").initialState;

var loggerMiddleware = createLogger({
  predicate: () => process.env.NODE_ENV === "development"
});

var createStoreWithMiddleware = redux.applyMiddleware(
  thunkMiddleware,
  loggerMiddleware
)(redux.createStore);

function createStore() {
  var store = createStoreWithMiddleware(HSApp, initialState);

// Hot reloading with Redux must be handled explicitly and manually : https://github.com/rackt/react-redux/releases/tag/v2.0.0
// Here's how to do it with liveReactload : https://github.com/milankinen/livereactload#reacting-to-reload-events
// If not done, a big warning appears in the console
// TODO: Solve this hot reloading issue, sometimes the big warning appears.
  if (process.env.NODE_ENV === "development") {
    if (module.onReload) {
      module.onReload(function() {
        console.log("> Module.onReload");
        var nextReducer = require("../reducers/index");
        console.log("nextReducer", nextReducer);
        store.replaceReducer(nextReducer.default || nextReducer);
        return true;
      });
    }
  }

  return store;
}

module.exports = createStore;
```

I'd love help to understand what I did wrong. As I returned `true` from the `module.onReload` callback, it should be accepted, but the failure seems to appear because apparently [it's not](https://github.com/milankinen/livereactload/blob/b2cb1b5c351871c0247cd65ae5989d40fc988081/src/client/handleChange.js#L48-L54).

**Comment by milankinen** [comment]
Hi @DjebbZ!

Are you using Babel 6? Babel 6 default exports must be imported under `default` field when using traditional `require("module_name")`. 

Please see: https://github.com/milankinen/livereactload/blob/master/examples/02-redux/store/configureStore.js#L17

**Comment by milankinen** [comment]
What does you `console.log("nextReducer", nextReducer);` print?

**Comment by DjebbZ** [comment]
Stupid me, `../reducers/index` exports an object, and the reducer is a property of this object. After correcting this mistake, and reloading the browser, I can edit everything and it hot reloads properly, apart from the reducer. I get the same error message than #64. I'll continue the discussion over there.

Closing here. Thanks for pointing out my silly mistake !

**Comment by milankinen** [comment]
Nice! :+1:
