### ISSUE TITLE
Without React

### ISSUE THREAD

**Issue by antoniobrandao** [milankinen/livereactload#109]
Is there any chance, even if remote, that something awesome like this can work without React ?

**Comment by milankinen** [comment]
Ahh sorry about the delay. The answer is yes. LiveReactload can be used without React *if* your application stores the state somewhere across reloads.

Pleas see Dan Abramov's [blog post](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.qsdvquym8)

**Comment by antoniobrandao** [comment]
@milankinen great, thanks! 👍
