### ISSUE TITLE
livereactload turning `module.exports = undefined` into empty object

### ISSUE THREAD

**Issue by callumacrae** [milankinen/livereactload#113]
Lodash is breaking with the following error when used through livereactload:

> Uncaught TypeError: Map is not a constructor

The cause seems to be that `_Map.js` in lodash is exporting `undefined`, but then in `_getTag.js`, `require('./_Map')` is receiving `{}`, causing a falsy check further down the file to fire incorrectly.

I faced the same problem in another scenario a while ago, so it isn't just lodash: although I can't remember the exact details.

This seems to be the line of code causing the problem: https://github.com/milankinen/livereactload/blob/master/src/requireOverride.js#L17

cc @djgrant (we are both trying to figure out a fix right now)

**Comment by apomortsev** [comment]
I'm facing exactly same issue. I found that the second and all subsequent require() calls on a module exporting undefined value return an empty object, for example:

`undef.js`:
<pre>
modules.exports = undefined;
</pre>

`usage.js`:
<pre>
var undef = require('./undef');
// undef === undefined

undef = require('./undef');
// undef === {}

undef = require('./undef');
// again, undef === {}
</pre>

Thanks.

**Comment by milankinen** [comment]
Ah gosh. This is definitely a bug. Thanks reporting it

**Comment by callumacrae** [comment]
Hey! This is affecting us at work, so we'd like to add a bounty to it (using Bountysource, unless you have an alternative you'd prefer). What do you think would be an appropriate amount? I'm not really sure how big this fix is: when I tried to fix it myself, I just ended up breaking everything!

**Comment by dolfelt** [comment]
I am experiencing this as well, though intermittent.

**Comment by milankinen** [comment]
Finally got my thesis ready! Going to take a look at this during this week.

**Comment by milankinen** [comment]
Fixed in `3.0.0`.

**Comment by callumacrae** [comment]
Amazing, thank you!

cc @djgrant
