### ISSUE TITLE
Test are broken on master due to a bug in propagation guards

### ISSUE THREAD

**Issue by ganemone** [milankinen/livereactload#114]
You can reproduce this easily by simply running the tests on master. Adding a log in test/app/site.js you can see it is reloaded on every change, and it should not be.

This breaks integration with redux, as the client side entry point is reloaded on every change, resetting the store back to its initial state.

**Comment by ganemone** [comment]
Somehow tests are passing on ci, but they consistently fail when I run them locally (npm2 && node 4.2.0). Regardless of the tests, I can reproduce the propagation issue consistently in an example project.

**Comment by milankinen** [comment]
Hmmm very strange. All tests pass with my computer.

What OS are you using?

**Comment by milankinen** [comment]
I definitely should re-write the whole module loading and re-loading. Gosh if I had time... My master's thesis has taken all of my time this month, but perhaps I get some time right after June to fix this whole module loading/propagation pipeline. 😥

**Comment by ganemone** [comment]
Running on osx. As far as I can tell, the reloading propagates up until unless it is manually told to stop via returning true in the module.onReload callback. If that is the expected behavior, I would expect the current tests to fail, since test/app/site.js does not implement module.onReload.

Not sure if this is the expected behavior, but it seems to work fine (with a redux application at least).

**Comment by milankinen** [comment]
Reload can also stopped if the module returns only React Componen(s), 'cause they can be patched and reloaded. If module returns also other objects/functions, then reload should bubble up to the parent component.

Propagation guard tests can be found from: https://github.com/milankinen/livereactload/blob/master/test/smokeTest.js#L92-L133

**Comment by milankinen** [comment]
Fixed in `3.0.0`.
