### ISSUE TITLE
Maximum recursion exceeds with livereactload@2.3.0-rc5

### ISSUE THREAD

**Issue by sassanh** [milankinen/livereactload#121]
I installed livereactload@2.3.0-rc5 after changing a module (tried on different types of modules) I get this error:

https://www.dropbox.com/s/mvet6ow1j6mabc4/Screenshot%202016-07-13%2016.52.14.png?dl=0

Let me know if I can provide more information about this.

**Comment by milankinen** [comment]
Thanks for reporting this! Do you get the same error message if you try `2.3.0-rc3`?

If you still get the error, could you turn debugging on (`-p [ livereactload --debug ]` if using CLI, `{debug: true}` if using JS API) and paste you console log?

**Comment by sassanh** [comment]
It happened with 2.3.0-rc3 as well, after enabling debug flag I found out the recursion is happening on 2 modules importing each other. After eliminating one of these modules it started working so I'm sure the problem is with import loop in modules. The logs in console are so huge, let me know if you still need it and I'll make a gist for it.

**Comment by milankinen** [comment]
Nice notice. Are those modules importing each other directly or are there any "intermediate" modules between those imports?

**Comment by sassanh** [comment]
They're importing each other directly.

**Comment by milankinen** [comment]
@sassanh Just released `2.3.0-rc6` which hopefully fixes this infinite recursion bug. Would it be possible to test whether the fix works in your case or not?

**Comment by sassanh** [comment]
@milankinen thank you. It's working with `react-router` and `redux` without errors  or warnings on `2.2.x`. It's been alright so far. I'll let you know if I find any problems.
