### ISSUE TITLE
Cannot connect to reload server

### ISSUE THREAD

**Issue by neemzy** [milankinen/livereactload#124]
Hi,

I just tried setting up the tool again and am now encountering the following message in my browser's console (tried in both up-to-date Firefox and Chrome): `Can't establish a connection to the server at ws://localhost:4474/.`

For the record, I'm setting up LiveReactLoad like this: `bundle.plugin(require('livereactload'), { port: 4474, host: 'localhost' });`

Cheers!

**Comment by milankinen** [comment]
Hi @neemzy! What does the console say when you start `watchify` with LiveReactLoad plugin?

**Comment by neemzy** [comment]
The connection occurs correctly when doing this, so it must be something on my side indeed :)

**Comment by milankinen** [comment]
@neemzy So did you manage to get it working? 😄

**Comment by neemzy** [comment]
@milankinen Actually, I did not (yet); I figure it has something to do with my Browserify build, but can't quite put my finger on it. Anyway, it doesn't seem related to your lib, so don't waste your time on this :) Cheers!
