### ISSUE TITLE
 Problem with bufferutil and utf-8-validate

### ISSUE THREAD

**Issue by neemzy** [milankinen/livereactload#125]
See [this issue](https://github.com/AgentME/browserify-hmr/issues/19) on a similar lib.

Is it considerable to make those two packages dependencies of `livereactload` to prevent users from having to require it themselves? (I'd perfectly understand a negative answer)

Cheers!

**Comment by milankinen** [comment]
Hi @neemzy!

Which LiveReactload version are you using? The new `3.x` series shouldn't use `ws` in browser side anymore. Or did I miss the question?

**Comment by neemzy** [comment]
Hi @milankinen, thanks for putting some time into this :) After testing again, it turns out you're right, I'm not running into this issue any longer. Sorry for the false alarm.
