### ISSUE TITLE
Add SSL support to WebSocket server

### ISSUE THREAD

**Issue by sajinshrestha** [milankinen/livereactload#126]
I'm trying to use `LiveReactload` over `https` but can't get it to work. Console shows the server is up and listening correctly. 

`[21:25:10.091] LiveReactload :: Reload server up and listening in port 4474...`
#### browser console error:

```
LiveReactload :: LiveReactLoad transform detected. Ready to rock!
card.js:37 WebSocket connection to 'wss://example.com:4474/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
#### npm script:

```
watchify index.jsx -t babelify -p [ livereactload --host='example.com' ] -o static/bundle.js
```

Any ideas on how I can troubleshoot this?

**Comment by sajinshrestha** [comment]
I'm guessing I need to pass `tls certificates` to [ws](https://github.com/milankinen/livereactload/blob/366bca57adc381ac395c0cd6ae0475bf48d630a1/src/browserify-plugin/server.js#L11) server, but not sure.

**Comment by milankinen** [comment]
Hmmm. The current implementation doesn't support certificates ATM but I think it wouldn't be so hard to implement by following e.g. this tutorial: http://www.chovy.com/web-development/self-signed-certs-with-secure-websockets-in-node-js

I have unfortunately so little time for open source at the moment so PR's are more than welcome! 😄   

Perhaps CLI options `--ssl-cert <certFilename>` and `--ssl-key <privateKeyFilename>` could do the job? 
* If both of them are given, then the backend could use HTTPS
* If only either of them is defined, then error/warning is displayed
* If neither of them is defined, then use the current implementation

**Comment by sajinshrestha** [comment]
Thanks, @milankinen. I'll give it a try.
