### ISSUE TITLE
cssmodulesify changes don't get reloaded

### ISSUE THREAD

**Issue by pixelass** [milankinen/livereactload#128]
## what is the issue?

When changing a file a css file the new css is not loaded
## expected behavior

When a css file is changed the browser should reload the css to apply the new styles
## what is actually happening?

Changes in CSS files trigger a reload but return "nothing to reload"

```
                        VM10550 main.js:389 
LiveReactload :: Bundle changed
                        VM10550 main.js:389 
LiveReactload :: Nothing to reload
```

When I refresh the browser the change is visible. Changes in js files work as expected
## Info
- `"livereactload": "^3.0.0"`

``` js
const b = browserify({
  entries: [inFile],
  plugin: [
    errorify,
    watchify,
    livereactload
  ],
  transform: [
    [ babelify, {
      presets: [
        'es2015',
        'stage-0',
        'react'
      ]
    }]
  ]
})
b.plugin(cssModulesify, {
  output: `${outFile}.css`,
  generateScopedName
})
```

**Comment by milankinen** [comment]
Thanks for you report @pixelass!

Could it be possible to provide a simple MVP example project having this issue so that I could investigate this more?

**Comment by pixelass** [comment]
Thx for answering.
This popped up late at night. I put it here to remind myself to make a scoped project to reproduce it.

I'll make a MVP later this week. (this is for a private project therefore a low priority on my side)

**Comment by pixelass** [comment]
I have experienced this acouple of times now. I think it is due to the way css-modulesify works. In my latest projects I use browser-sync on top of livereactload. That also takes care of the css loading for me. This can be reproduced in the boilerplate I mentioned in #150

**Comment by tsi** [comment]
Hi @pixelass, about your last comment, how did you set-up browser-sync on top of livereactload so that the CSS loading worked?
I'm trying to implement livereactload on an existing project that uses LESS preprocessor, my JS bundle reloads fine on-change but the styles do not.

**Comment by pixelass** [comment]
@tsi 
This is from the full repo of the example I added a while ago: https://github.com/pixelass/redux-react-boilerplate/blob/master/scripts/serve.js

**Comment by milankinen** [comment]
@pixelass nice that should work indeed! 👍

**Comment by milankinen** [comment]
May I close this issue since it seems to be resolved?
