### ISSUE TITLE
Working with rails

### ISSUE THREAD

**Issue by huan-ji** [milankinen/livereactload#132]
Hello, 

I am currently trying to get this to work with rails, and am running into some issues. I am able to serve the bundle to the browser through rails, and it does appear to open up a websocket and reload changes, but no changes actually are made to the bundle in the browser. Changes are however made to the bundle file locally. 
![image](https://cloud.githubusercontent.com/assets/13550952/19161706/b0d2f7f8-8ba9-11e6-8ee8-0811cb50b7e8.png)

As you can see above, the websocket appears to be working and receiving changes, but the browser bundle file does not reflect those changes. Any help appreciated

**Comment by huan-ji** [comment]
Okay I managed to get the errors down to just this one, but have no idea why it's occurring:
![image](https://cloud.githubusercontent.com/assets/13550952/19162645/944991ec-8bad-11e6-9630-dae0642288be.png)
`{
  "presets": ["es2015", "react"],
  "plugins": [
    ["react-transform", {
      "transforms": [{
        "transform": "livereactload/babel-transform",
        "imports": ["react"]
      }]
    }]
  ]
}
`
The above is what my .babelrc looks like. Don't understand why it wouldn't be recognizing livereactload/transform...

**Comment by milankinen** [comment]
Hi @huan-ji and sorry, I missed this issue completely!

It seems that you're using CoffeeScript whereas LiveReactload (or technically `react-transform`) is meant to be used with Babel only. That's probably why LiveReactload is not working with your project.

**Comment by milankinen** [comment]
Is this issue still valid or can I close this? @huan-ji

**Comment by huan-ji** [comment]
Yeah feel free to close it. Thanks for the response!

**Comment by milankinen** [comment]
Thanks! 👍
