### ISSUE TITLE
Reload Complete, but no changes in HTML

### ISSUE THREAD

**Issue by srrvnn** [milankinen/livereactload#134]
Hello folks, I need some help to figure out why hot loading is not working in my case. 

I have everything setup like in the README.md and am using this command: 

`watchify public/js/app.js -o public/js/bundle.js -dv -p livereactload & node server.js`

When I edit and save [a component file](https://github.com/srrvnn/rst/blob/master/public/js/components/LinksList.react.js) in my project:

in the terminal I see: 

`Notify clients about bundle change`
`4572912 bytes written to public/js/bundle.js (1.63 seconds)`

in the browser console I see: 

`LiveReactload :: Bundle changed bundle.js:389`
`LiveReactload :: Applying changes... bundle.js:215` 
`> Reload module    :: /Users/srrvnn/Projects/rst/public/js/components/LinksList.react.js`
`> Patch component ::  _component bundle.js:389` 
`LiveReactload :: Reload complete!`

and yet the browser HTML does not change to show the hot load. 

what am I missing?

**Comment by milankinen** [comment]
Hi @srrvnn and sorry for the delayed answer!

I don't see any reason why your example shouldn't work. I actually cloned the repo and tested it and it indeed doesn't reload. This is definitely a bug but the reason is still unclear for me... 😁

**Comment by octalmage** [comment]
I'm seeing the same thing, still looking into it but I wanted to chime in.

**Comment by milankinen** [comment]
@octalmage Do you have any simplified example project (open source) re-producing this issue?

**Comment by EugeneZ** [comment]
The repo seems to be gone. I wish it was still around. I wonder if it would work with the new beta. @milankinen Do you happen to still have the clone?

**Comment by milankinen** [comment]
Nope. Unfortunately 😕

**Comment by milankinen** [comment]
I'm closing this one. Feel free to comment if the issue still exists and I'll re-open this.
