### ISSUE TITLE
(notsureif) Question about implementation, or bug.

### ISSUE THREAD

**Issue by arcticShadow** [milankinen/livereactload#137]
I'm attempting to integrate this into my organisations build tooling - which does lots of stuff on the way through specific to our org, and abstracts it away from n00bs.

We use a combination of browsersync, breowserify and babel (among many other things) I already know that I have something to tweak in our watch step to make this work, but right now i have an issue loading anything when i include the browserify plugin. 

Instead of loading things from my bundle, everything is attempting to load individually.  As far as i can tell it's due to the way the bundle has been created. Anyone have ideas? I was wondering if its related to #123

**Comment by milankinen** [comment]
I released version  [`3.1.1`](https://github.com/milankinen/livereactload/releases/tag/3.1.1), does it fix this problem?

**Comment by milankinen** [comment]
Closing this for now. If the issue still remains, I'll re-open this.
