### ISSUE TITLE
Source map path/filename issues

### ISSUE THREAD

**Issue by pizza2code** [milankinen/livereactload#141]
When I updated from livereactload 2.2.2 to 3.1.1, the first thing I noticed was that my Typescript sourcemaps seemed to disappear.  On closer examination, the sourcemaps are still intact, but console shows the path & filename of the compiled Javascript rather than the Typescript source filenames.  

Also, the source browser is incredibly cluttered, with each file given its own separate directory prefaced by what looks like a GUID:

![livereactload_3_1_1](https://cloud.githubusercontent.com/assets/15824044/21054625/69b806ee-bdfc-11e6-8595-4e94f5479e2e.jpg)

When I revert to 2.2.2 these issues disappear.  May be related to #127 ?

**Comment by milankinen** [comment]
Hmmm. I have never used LiveReactload with TS so hard to say... Do you have any minimalistic project with LiveReactload+TS combo re-producing this issue?

**Comment by pizza2code** [comment]
I would have to create a minimal project, I don't have any on hand (and what I do have on hand is not FOSS).

The issue appears to be this line:
https://github.com/milankinen/livereactload/blob/master/src/browserify-plugin/main.js#L110
`converter.setProperty('sources', [file.replace(basedir, hash)])`

In that code, `file` is the filename given to Browserify (ex: filename.js).  However, in all compile-to-JS languages, the source filename != the file given to Browserify.  If I call `converter.getProperty('sources')` directly before that line, I see the appropriate Typescript filename & path.

The hashes in the path are a separate issue, and seem to be intentional based on this comment: https://github.com/milankinen/livereactload/pull/138#issue-191432807

**Comment by milankinen** [comment]
Fixed in [`3.1.2`](https://github.com/milankinen/livereactload/releases/tag/3.1.2). Can we close this issue?

**Comment by pizza2code** [comment]
Indeed.  Thanks! :)
