### ISSUE TITLE
Option to disable transform warning

### ISSUE THREAD

**Issue by pizza2code** [milankinen/livereactload#144]
Hello again! :)

I'm using livereactload to bundle the output of compiled Typescript.  Since the Typescript compiler has watch mode and JSX transformation, I find the babel React transform unnecessary. Similarly, someone may wish to manually transform the JSX before sending their Javascript to Browserify.  For cases like this, I propose a new option:

#### --no-transform
Will skip the check for Babel React transform & display no warning.
API: opts.transform - When set to false, is equivalent to the above switch.

I can make the simple changes.

**Comment by milankinen** [comment]
Hi!

Good suggestion, just make a PR if you wish. 😄  However, could we use some other option name because "transform" is a bit ambiguous (Browserify transform vs Babel transform). How about e.g. `--no-babel`?

**Comment by pizza2code** [comment]
I hear you. --no-babel works!

**Comment by milankinen** [comment]
Included in [`3.2.0`](https://github.com/milankinen/livereactload/releases/tag/3.2.0)!

**Comment by EugeneZ** [comment]
Without the babel transform, your components are not being proxied and hence state is lost. Are you manually proxying them somehow? Or are you simply ok with getting simple non-React-specific HMR?

**Comment by pizza2code** [comment]
I've been keeping state with React-Redux and reacting to the module.onReload event.
