### ISSUE TITLE
Add some kind of smoke tests

### ISSUE THREAD

**Issue by milankinen** [milankinen/livereactload#15]
Some automatic regression testing is needed so that I don't have to check each example manually before releasing a new version. The tests don't need to be runnable headlessly - just some kind of command line script that uses (if necessary) for example browser extensions to ensure that livereloading works. Running that script is much quicker than clicking all the examples by hand. :)

What would be the best way to implement those tests? Any ideas?

Here are my initial thoughts:

* Use examples as tests
* Zombie/PhantomJS/Selenium?

**Comment by mattdesl** [comment]
[smokestack](https://github.com/hughsk/smokestack) + tape is another suggestion 

e.g. 
`browserify test.js | tap-closer | smokestack | faucet`

**Comment by Munter** [comment]
mocha with jsdom is enough to run react tests, which makes the setup a lot simpler, a lot faster and runnable locally without any crazy browser booting and socket connections.

Assuming that the livereload API is properly tested you wouldn't even have to implement modifications of files, triggering watches and sending the socket update. You could just trigger the livereload client with your updated component source code and test that changes were applied while state was kept

**Comment by milankinen** [comment]
Hmmmm, jsdom seems very promising. I have to take a better look at it.

**Comment by milankinen** [comment]
Added in `0.4.0`
