### ISSUE TITLE
Add link to up-to-date Redux example

### ISSUE THREAD

**Issue by pixelass** [milankinen/livereactload#150]
The redux example is outdated. Most of the libraries around React changed.

I just included your redux-example in my new boilerplate. 
I ported all the tests to AVA and Sinon and used a different coding style but besides that, it mirrors the example. The boilerplate is fully tested.

While developing I struggled to get it all working so I decided to look into your example and saw that its dependencies are old and newer versions have breaking changes.

My boilerplate is fully covered, and documented.
It includes livereactload and browser-sync (they play well together)

I use browserify and try to keep everything else vanilla.
The only non-vanilla part is css-modules which is almost default for react projects and can easily be removed

The scripts run via js-file instead of npm scripts since they are easier to read and modify.

I'm not sure if this is even interesting for this repo but maybe you can link it so others can find/use it.

**Repo:** https://github.com/pixelass/redux-react-boilerplate

Cheers Greg

(Not sure if I can just open a PR to add it to the readme.)

**Comment by milankinen** [comment]
Hi Greg!

Your repo looks interesting. Could I use it as a basis for the new, updated example in future? Meanwhile, I see no problem in linking to your repo. 👍 

And yeah, sure! You can make a PR adding an out-of-date notice to redux example's README and linking to your repo as an example of an up-to-date project.

**Comment by pixelass** [comment]
Feel free to use it or even integrate it. That's what it's made for. ;)
I'm still thinking about removing browser-sync due to insecure dependency status and its size. 
My goal was to make a close to complete boilerplate because I myself often struggle setting these things up over and over again. I paid some attention to allow detaching parts so you should be able to easily remove some weight.

I'm totally fine with creating a PR for that myself. It would basically be a swap of the old folder with a project generated from my boilerplate.
