### ISSUE TITLE
template literals in npm module

### ISSUE THREAD

**Issue by BarryThePenguin** [milankinen/livereactload#155]
Looks like the published code in npm still has template literals. Using `livereactload@next` in IE11 ends up with a `SCRIPT1014: Invalid character` error

See https://unpkg.com/livereactload@4.0.0-beta.1/lib/reloading.js, specifically 

```js
console.warn(`LiveReactload: You are providing two arguments to the module.hot.onUpdate hook, and we are
                ignoring the first argument. You may have copied and pasted a webpack hook. For compatibility, we are
                accepting this, and it will probably work, but please remove the first argument to avoid confusion.`)
```

**Comment by BarryThePenguin** [comment]
There's a `"postcompile": "cp src/reloading.js lib/"` step in `package.json` that reverts the babel compiled file. That could be removed. Or `src/reloading` could be made to work without template literals (or any other ES6 features)

**Comment by EugeneZ** [comment]
Good catch. `reloading.js` is not intended to be transpiled. My bad. #156 fixes this!

**Comment by milankinen** [comment]
Oh nice! 👍  My fault, I reviewed the code but didn't notice this

**Comment by milankinen** [comment]
[`4.0.0-beta.2`](https://github.com/milankinen/livereactload/releases/tag/4.0.0-beta.2) (also tagged as `next`)
