### ISSUE TITLE
Does not work with browserify-global-shim

### ISSUE THREAD

**Issue by zavr-1** [milankinen/livereactload#164]
I'm loading the React lib via CDN and using https://github.com/rluba/browserify-global-shim to expose it to require, and it works for my `node_modules` but it doesn't work for this library:

```js
var _react = _interopRequireDefault((window.React)) // my components
var React = require('react'); // /node_modules/react-hot-loader/dist/react-hot-loader.development.js
```

I think it might be to do with the order in which plugins are added and transforms are run?

My use of browserify 

```js
const globalShim = bgs.configure({ react: 'React' })

const b = browserify({
    entries: [path],
    cache: {},
    packageCache: {},
    plugin: [watchify, livereactload],
    debug: true,
    transform: [globalShim],
    extensions: ['.jsx'],
  })
```

**Comment by zavr-1** [comment]
OK I figured it out, it needs to be specified as a global transform.
```js
```

**Comment by milankinen** [comment]
Good job! 👍
