### ISSUE TITLE
BrowserSync compatibility

### ISSUE THREAD

**Issue by geoRG77** [milankinen/livereactload#17]
Hey, thanks for this, I really would like to use hot reload with Gulp/Browserify and not Webpack.

I got notification working w/ watchify but the problem is it doesn't refresh the browser. I'm using Rails app with BrowserSync, not Express.

```
[20:58:50] 2458336 bytes written (1.00 seconds)
LiveReactload: sending reload request to 1 clients
```

```
Uncaught TypeError: Cannot read property '1' of null       livereload-client.js:24
```

**Comment by milankinen** [comment]
Ok, I'll investigate this. Could you create a simple example project setup which produces this problem?

**Comment by geoRG77** [comment]
Thanks! 

I created it: https://github.com/geoRG77/react-hot-reload

**Comment by milankinen** [comment]
Ok, I got it. BrowserSync generates JavaScript file url `http://localhost:3001/assets/app.js?body=1:1803:17` which crashes the reloading script url detection (query parameters not expected).

**Comment by milankinen** [comment]
Created new issue for this one. Continuing discussion there.
