### ISSUE TITLE
Fix reload client crash when bundle url has query parameters

### ISSUE THREAD

**Issue by milankinen** [milankinen/livereactload#20]
Original issue #17.

BrowserSync generates url that contains query parameters when reload client tries to parse bundle url from the thrown stacktrace, it gets the following string:
```
 "Error
        at getScriptURL (http://localhost:3001/assets/app.js?body=1:1812:11)
        at WebSocket.module.exports.init.ws.onmessage (http://localhost:3001/assets/app.js?body=1:1803:17)"
``` 
Which causes the regex parser at `livereload-client.js` 

Regex parser must be improved to accept also urls with query parameters.

**Comment by geoRG77** [comment]
Thanks, I created PR with fix: https://github.com/milankinen/livereactload/pull/21

Livereload works now, but I thought I would be able to edit following jsx without changing the state of the component.
```
import React from 'react'

export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  render() {
    return (
      <a className='btn btn-primary' onClick={this.tick.bind(this)}>
        Click here #{this.state.count}
      </a>
    );
  }
}
Counter.propTypes = { initialCount: React.PropTypes.number };
Counter.defaultProps = { initialCount: 0 };

React.render(<Counter />, document.getElementById('react-test'));
```

**Comment by milankinen** [comment]
The problem in your example is that your `Counter` component is private, thus reloading loses its state. Please see `examples/02-private-components` for more information
