### ISSUE TITLE
Adding livereactload as global transform when no react peer causes error `module.exports=;`  - ParseError: Unexpected token

### ISSUE THREAD

**Issue by jeffbski** [milankinen/livereactload#22]
In following the README it looked like the safe thing to do is to add livereactload as a global transform even though I am not using anything that has a peer dependency, so that if I were to add something later, it would already be set properly.

However in doing that I get a ParseError for the generated code `module.exports=;`

**So apparently you can't use it as a global transform if you don't have any react peer dependencies.**

**Switching livereactload to a normal browserify transform fixes the problem.**

I wonder if there is anyway this could be improved or at least have an informative error message.

```
/Users/jeff/working/react-iso-router-im-curs-rx3-transition-livereload/node_modules/browserify/node_modules/crypto-browserify/node_modules/diffie-hellman/lib/primes.json:1
module.exports=;require=(function(req){if(typeof(window)!=="undefined"){return(function(name){if(name==="react")return(function(){window.__livereactload=window.__livereactload||{};window.__livereactload.React=window.__livereactload.React||req("react");return(window.__livereactload.React);})();if(name==="react/lib/ReactMount")return(function(){window.__livereactload=window.__livereactload||{};window.__livereactload.ReactMount=window.__livereactload.ReactMount||req("react/lib/ReactMount");return(window.__livereactload.ReactMount);})();if(name&&name.indexOf("react/")===0)return(function(name){window.__livereactload=window.__livereactload||{};window.__livereactload["__reactExport_"+name]=window.__livereactload["__reactExport_"+name]||req(name);return(window.__livereactload["__reactExport_"+name]);})(name);return(req(name));})}else{return(req(name));}})(require);{
               ^
ParseError: Unexpected token
```

It looks to me like the error is coming from `module.exports=;` (missing some value before the semicolon)

The browserify parts of my package.json are:
```json
  "browser": "src/browser.jsx",
  "browserify": {
    "transform": [
      "babelify"
    ]
  },
```

My watchify command from my npm run watch

```bash
watchify . -d --extension=.jsx -g livereactload -v -o dist/bundle.js
```

Here are the versions of the packages I am using:

```
npm ls browserify watchify livereactload react babelify
react-form-im@1.0.0 /Users/jeff/working/react-iso-router-im-curs-rx3-transition-livereload
├── babelify@5.0.4
├── browserify@9.0.3
├── livereactload@0.2.4
├── react@0.13.1
└── watchify@2.4.0
```

**Comment by milankinen** [comment]
Hmmm I think this is not related to React peer dependency issue at all.

When I look at your example code it seems that the error comes from the json file
`/Users/jeff/working/react-iso-router-im-curs-rx3-transition-livereload/node_modules/browserify/node_modules/crypto-browserify/node_modules/diffie-hellman/lib/primes.json:1`

This seem to be a bug. LiveReactload should **not** transform json files, I'll make a more generic ticket from this one.
