### ISSUE TITLE
not reloading components with shared-root

### ISSUE THREAD

**Issue by gilbarbara** [milankinen/livereactload#26]
I'm using `react-router` with shared-root for public/private paths.

```js
// routes.js
<Route handler={App}>
	<Route handler={PublicApp}>
		<Route name="login" handler={LoginApp}/>
		<DefaultRoute handler={LoginApp}/>
	</Route>
	<Route handler={PrivateApp}>
		<Route name="dashboard" handler={DashboardApp}/>
		<DefaultRoute handler={DashboardApp}/>
		<NotFoundRoute handler={NotFound}/>
	</Route>
</Route>
```

```js
//privateApp.js
var PrivateApp = React.createClass({
    contextTypes: {
        router: React.PropTypes.func
    },

    render: function () {
        return (
            <div>
                <Sidebar/>
                <Header/>
                <RouteHandler/> // <--- this
                <Footer />
            </div>
        );
    }
});
```

If I change anything on `config.js` or its direct child `privateApp.js` I get a hot reload, however if I edit any of the grandchild like `dashboardApp` the watchify task run and LiveReactload server log the reload to clients message but nothing changes on the page.

**Comment by milankinen** [comment]
I think I got it now. Accidentally tried to inject LiveReactload to transient dependencies (which were required during the initialization). Fix coming: https://github.com/milankinen/livereactload/commit/fcd6929b88981c578f6ef3d3b6cb370fc09247a5

**Comment by milankinen** [comment]
Hmmm.. interesting. Could you create a minimal example project producing this behaviour so that I can investigate more about this issue?

**Comment by gilbarbara** [comment]
hey,

I was setting up the example and I think I found the problem..
I'm using the `PureRenderMixin` in my components and since nothing has changed in the state, `shouldComponentUpdate` returns false.

Is there a way to `forceUpdate` while using this transform so my I don't have to change my flow just for the development cycle?

**Comment by milankinen** [comment]
In fact, `forceUpdate` should be called every time when reloading occurs (see https://github.com/milankinen/livereactload/blob/master/lib/browser/deps/force-update-app.js) **unless** you are using `onLoad` function from `livereactload-api`. 

I going to look at that `PureRenderMixin` case.

**Comment by gilbarbara** [comment]
@milankinen 
I'm not using the `livereactload-api` in my project. Just the `PureRenderMixin`

**Comment by milankinen** [comment]
Weird... React invoked `shouldComponentUpdate` during force update even though documentation says otherwise. Should investigate this more and mayhaps raise an issue.

However, this should now be in version `0.5.2` (released 5 mins ago): `PureRenderMixin` components reloading works with React `0.12.x` and `0.13.x`.

**Comment by milankinen** [comment]
Since no responses received, I'll close this one
