### ISSUE TITLE
grunt integration example

### ISSUE THREAD

**Issue by kidwm** [milankinen/livereactload#28]
I know there is an example with gulp, but could you also add grunt in example?
Thanks.

**Comment by milankinen** [comment]
Ok, I'll add that

**Comment by chrisbodhi** [comment]
Any progress to share on this request?

**Comment by milankinen** [comment]
Can't promise 100% but hopefully included in this Sunday's release.

**Comment by milankinen** [comment]
Added. Sorry for delay, didn't make it in Sunday. :-/

See https://github.com/milankinen/livereactload/tree/master/examples/05-build-systems
