### ISSUE TITLE
What's new in 0.4?

### ISSUE THREAD

**Issue by duncanmak** [milankinen/livereactload#29]
Do you have release notes for 0.4?

**Comment by urb4n1us** [comment]
https://github.com/milankinen/livereactload/blob/master/CHANGELOG.md

**Comment by milankinen** [comment]
Also: 0.5.0 coming soon! 

* Extremely simple monitoring support (instead of that ugly bash spaghetti)
* Automatic detection of inner React classes

**Comment by gilbarbara** [comment]
:+1:

**Comment by milankinen** [comment]
New version released, see `CHANGELOG.md` for more details. :wink:
