### ISSUE TITLE
"Unexpected token <" using babelify + livereactload

### ISSUE THREAD

**Issue by Kureev** [milankinen/livereactload#30]
Hi all,

I'm trying to run `livereactload` with 
```bash
watchify test.js -t babelify -t livereactload -o bundle.js -v
```
and monitor with 
```bash
livereactload monitor bundle.js
``` 
But when I change a file and bundle re-builds, on the client I receive a command to apply changes, but during this process I got following error:

<img src="http://i62.tinypic.com/15nlq8l.png" />

When I try to debug it, I see that for some reason it tries to process `index.html` and this error is about `<!DOCTYPE html>` string and every string with `<>`. What's wrong?

**Comment by Kureev** [comment]
Seems the problem was because I haven't run the server and used direct link to static file

**Comment by notduncansmith** [comment]
It would be really awesome to see a real resolution to this issue.

I'm trying to use `livereactload` with Electron (formerly Atom Shell) and I can't really work around the static file limitation.

**Comment by milankinen** [comment]
Created new generic issue for this one. `file:///` bundles should definitely be supported
