### ISSUE TITLE
sending reload request to 0 clients

### ISSUE THREAD

**Issue by Strajk** [milankinen/livereactload#31]
Hi there, I would love to try this magic repo but I'm unable to connect browser to livereactload (probably)

Watchify is running and it's working fine
```
watchify app/scripts/app.js -o .tmp/scripts/bundle.js -v
1522078 bytes written to .tmp/scripts/bundle.js (11.65 seconds)
1522078 bytes written to .tmp/scripts/bundle.js (0.37 seconds)
1522078 bytes written to .tmp/scripts/bundle.js (0.24 seconds)
```

LiveReactLoader is also running fine
```
node_modules/.bin/livereactload monitor -n .tmp/scripts/bundle.js & wait
[1] 14407
LiveReactload: server listening in port 4474
LiveReactload: sending reload request to 0 clients
LiveReactload: sending reload request to 0 clients
LiveReactload: sending reload request to 0 clients
```

Chrome live-reload icon is black
![cheap flights czech republic - anywhere at skypicker com 2015-04-29 16-57-14](https://cloud.githubusercontent.com/assets/697301/7393927/cb3981c8-ee90-11e4-9137-40c7d6a32c9a.png)

Desktop notifications are working

But I'm still getting `LiveReactload: sending reload request to 0 clients`...

Any ideas how to debug this more?

**Comment by Strajk** [comment]
It's working!!!
But I don't believe my eyes, it seems like some kind of crazy magic!!! :rocket:

**Comment by milankinen** [comment]
Nice! Happy coding. :wink:

**Comment by revolunet** [comment]
so what happened ? :)

**Comment by Strajk** [comment]
@revolunet I honestly don't remember exactly, I only remember it was some stupid mistake :)

Here's my working Grunt config now:
```
shell:
			browserifyServer:
				command: [
					'watchify app/scripts/app.js -g livereactload -o .tmp/scripts/bundle.js -v &'
					'node_modules/.bin/livereactload monitor -n .tmp/scripts/bundle.js &'
					'wait'
				].join(' ')
```
