### ISSUE TITLE
Hardware issues

### ISSUE THREAD

**Issue by tsm91** [milankinen/livereactload#33]
Hello, I implemented example 05-build-systems (the exact same code), and it is slow but most probably because it is eating up my hardware. 

Here is my [gulpfile.js](https://gist.github.com/TheSpiritMolecule/71235522048bc4d6b154), maybe you can spot something fishy there.

![screen shot 2015-05-20 at 22 51 23](https://cloud.githubusercontent.com/assets/4459551/7736317/306c4cd4-ff43-11e4-86c4-6cab9064b698.png)

**Comment by milankinen** [comment]
Thanks! I'll investigate this one. This is definitely not normal behaviour. Thanks for providing the gulpfile.

**Comment by TheSpiritMolecule** [comment]
I have to admit since then i checked out webpack and use it. But I think the problem might be, I only made one bundle and it is bundling in the vendor files and all their dependencies and thus it is watching a huge dependency tree

**Comment by milankinen** [comment]
Closing this one since there is no new reports recently
