### ISSUE TITLE
app.js?__livereactloadPreventCache=1432506868384 won't be served by many simple hosting solutions

### ISSUE THREAD

**Issue by slorber** [milankinen/livereactload#34]
Hi,

GET http://localhost:8080/app.js?__livereactloadPreventCache=1432506868384 net::ERR_CONNECTION_REFUSED

I host locally my SPA app with a simple function like:

```
function hostit(){
  PORT=${1:-'8080'}
  echo "Will try to host your directory $pwd at http://localhost:$PORT"
  python -m SimpleHTTPServer $PORT
  # http-server -a localhost -p $PORT --cors
}
```

Both `SimpleHTTPServer` and `http-server` seems to have issues when a queryString is added to the static file.

http://localhost:8080/app.js will be served, but not http://localhost:8080/app.js?xxx=yyy

It would be great if the querystring to prevent caching could be replaced with something else, or at least being able to bypass it would be great

**Comment by slorber** [comment]
When removing the cacheBust it seems to work better but I have other troubles :)

**Comment by milankinen** [comment]
Thanks for reporting this one! I'll add an option which can disable the cache busting.

**Comment by milankinen** [comment]
I created more generic issue for this. I'll close this one.
