### ISSUE TITLE
lrApi.onReload callback fired only the first time

### ISSUE THREAD

**Issue by slorber** [milankinen/livereactload#36]
Hi,

I manage all of my state outside of React as a global json object (no this.setState() is used).

My app is split in app.js and appLibs.js. I want hot reload for stuff in app.js, not libs.

My app.js contains:

```
console.error("app reloaded!");
LiveReactLoadApi.onReload(function() {
    console.error("test");
});
```

When app is launched, it prints `app reloaded!`
When I modify something, it prints `test`
When I remodify one or many times something, it prints nothing.

But it reloads an app.js file on every change (and call forceUpdate client method).

It seems on the subsequent calls to `executeReloadCallbacks` I have 0 registered callbacks.
Also I'm surprised that it does not print `app reloaded!` on every app.js reload.

I tried to put LiveReactLoadApi on the lib bundle so that it is not reloaded but it did not change anything.

Can you please document better how the `lrApi.onReload` should be used. 
Should the lrApi be in the reloaded bundle?
Any idea why the callbacks are removed?

**Comment by milankinen** [comment]
Very strange. At least `app reloaded!` should be printed every time when the bundle is reloaded.

Do you have any errors during the bundle reloads? Are both `app.js` and `appLibs.js` in the same bundle or are they separate bundles?

**Comment by milankinen** [comment]
Closing this one 'cause `livereactload-api` is deprecated and should not be used anymore with `2.x.x` series
