### ISSUE TITLE
browserSync compatibility

### ISSUE THREAD

**Issue by gilbarbara** [milankinen/livereactload#37]
I got livereactload 0.4 to work with browserSync but since 0.5 isn't working at all. 
Is it possible?

**Comment by milankinen** [comment]
Hmmm. Can you give more details? Do you get any errors to the console? 

I just tried your previous codes (https://github.com/geoRG77/react-hot-reload) with version `0.5.2` and it worked fine.

**Comment by gilbarbara** [comment]
hey!

No errors, I just get `sending reload request to 0 clients` 
And that's not my code.

I've added the transform to browserify with:
```
bundler = browserify({
    transform: watch ? [['livereactload', {global: true}], 'reactify'] : ['reactify']
});
``` 
and I'm starting it with:
```
if (watch) {
    lrload.monitor('.tmp/scripts/app.js', {displayNotification: true});
}
```
and in the index.html:
```
<!-- build:js({app,.tmp}) scripts/app.js -->
<script src="scripts/app.js"></script>
<!-- endbuild -->
```
Maybe I need to change the script path to something else?

**Comment by milankinen** [comment]
If you open JavaScript console from your browser, what is the value of `window.__livereactload`?

**Comment by hamczu** [comment]
I use livereactload with browserSync and I do not have any issues - I think this is not a bug but issue related with your setup.

**Comment by gilbarbara** [comment]
I will try again in the weekend with the new version and post it back
