### ISSUE TITLE
lrload.React.Component is undefined

### ISSUE THREAD

**Issue by WishCow** [milankinen/livereactload#4]
I'm trying to setup livereactload, by following the readme, however, I see this in the firebug console when I make a change to the files:
```
TypeError: lrload.React.Component is undefined
lrload.React.Component.prototype.forceUpdate.call(instance._instance)
```

In the console that is running the watch.sh script I see:
```
LiveReactload: new client connected
745622 bytes written to static/bundle.js (0.22 seconds)
LiveReactload: sending reload request to 1 clients
```

I had to modify the watch.sh script a bit, I added --extension, and -t reactify, is it possible those are causing problems? Here is the full script:

```bash
{ { node_modules/.bin/watchify static/js/index.jsx --extension=.jsx -v -t reactify -t babelify -t livereactload -o static/bundle.js 1>&2; } 2>&1 \
  | while read result; do
    echo "$result"
    [[ "$result" =~ ^[0-9]+[[:space:]]bytes[[:space:]]written  ]] && node_modules/.bin/livereactload notify
  done
} &

node_modules/.bin/livereactload listen
wait
```
**Edit**
I just tried without the --extension=.jsx, same thing.

**Comment by milankinen** [comment]
Hmmm, strange. Which version of React are you using?

**Comment by WishCow** [comment]
0.12

**Comment by milankinen** [comment]
Aaah ok, that would explain the problem. I've tested only with React 0.13 so older version could cause this problem..

Can you upgrade your React version and check if the problem disappears? 

I created an issue https://github.com/milankinen/livereactload/issues/5 about React 0.12 support

**Comment by WishCow** [comment]
Unfortunately no, not at the moment, 0.13 breaks my app :(

https://github.com/facebook/react/issues/3418

**Comment by milankinen** [comment]
Ok, I've released version `0.2.2` which should fix this problem. Can you confirm if this exists anymore?

**Comment by WishCow** [comment]
The error disappeared, but the live reload does not happen. The CLI console stays the same.

**Comment by milankinen** [comment]
Okay. Does your terminal give you any message like `LiveReactload: sending reload request to 1 clients` when you save your file? If that line exists, then your bundle is being reloaded but there is something that prevents the new application to be rendered.

When I run the example 02 with React 0.12.2 and Firefox, everything works well.

Is it possible to see you code that I can investigate this more?

**Comment by WishCow** [comment]
Yes, I see this in the terminal:
```
LiveReactload: new client connected
597124 bytes written to static/bundle.js (0.15 seconds)
LiveReactload: sending reload request to 2 clients
LiveReactload: new client connected
```

(It's 2 clients, because I'm also testing with Chrome.)
The code I'm testing with is just a skeleton, I'll upload it in a sec to github.

My watchify version is 2.6.2.

**Comment by WishCow** [comment]
Figured it out. For some reason, Firefox was pulling out the bundle.js file from BFCache for my "normal" project, but not for the skeleton one. After I ticked "disable browser cache" in the net panel in Firebug, it works.

Might be worth mentioning in the readme?

**Comment by milankinen** [comment]
Yes, I'll put that in the next release
