### ISSUE TITLE
Doesn't work with React-jss

### ISSUE THREAD

**Issue by chrisjaure** [milankinen/livereactload#44]
Hey, I love this plugin! Definitely is one of my favorites when working with react.

Is there any chance you could take a look at what it would take to make it work with https://github.com/jsstyles/react-jss?

I'm guessing the problem is similar to your "When does it not work" example, but I'm not sure how to go about fixing it.

Also there already appears to be React Hot Loader support. Is it possible to conditionally add Livereactload support in a similar way? Seems like it would need to add livereactload-api as a dependency.

**Comment by milankinen** [comment]
Yeah, if it works with React Hot Loader then it can be supported with LiveReactload. 

Can you describe: how are you using the `react-jss` in your app and what happens if you use it with LiveReactload (Got error messages? Nothing happens? Else?)?

**Comment by chrisjaure** [comment]
Thanks for your help @milankinen!

The error I get out of the box when using more than one component that uses react-jss is `Uncaught TypeError: Cannot read property 'classes' of null` because on reload, `this.props.sheet` is null. I did a little debugging and I'm guessing that's primarily because `refs` and `sheet` here get reset: https://github.com/jsstyles/react-jss/blob/master/src/index.js#L5-L6

It seems react-jss needs global state to track stylesheet usage for multiple components of the same type.

Here is the React Hot Loader support, but that never seemed to be called for me: https://github.com/jsstyles/react-jss/blob/master/src/index.js#L49-L53

Here's a small example of how I'm using it: https://github.com/dhmncivichacks/isitrecycling/blob/jss/src/components/section.js

Finally, I tried hacking some support in my own fork, but ran into strange issues where the wrong stylesheet would get applied to the wrong component: https://github.com/chrisjaure/react-jss/commit/f30261fd82cb7d090844a1ab9d1113dabc3b2343

If you think what I have there is the right approach, I can try to debug it some more, otherwise any hints would be very appreciate! Thanks!

**Comment by milankinen** [comment]
Thanks for the detailed feedback. I'm investigating this one but found nothing yet. Will notify you when new info is available

**Comment by milankinen** [comment]
Could you check if this problem is still present in the brand new `2.0.0-alpha2` version? https://github.com/milankinen/livereactload/tree/2.x.x

**Comment by chrisjaure** [comment]
Hey @milankinen, I'm not actually using react-jss anymore, but I'll try to create a simple use case and update this ticket with the results. Thanks!
