### ISSUE TITLE
Doesn't work over https

### ISSUE THREAD

**Issue by chrisjaure** [milankinen/livereactload#48]
The websocket connection is rejected because it's not secure when using https, due to the hard-coded protocol here: https://github.com/milankinen/livereactload/blob/master/lib/browser/deps/livereload-client.js#L8

Should check whether to use `ws` or `wss`.

**Comment by milankinen** [comment]
This would also require TLS support for LiveReactload server. My WebSocket knowledge is not enough for making "development" WS server with TLS and custom certificate support.

Could any WebSocket guru give some advices how to create a WS server (with custom certificate) that accepts TLS connections?

**Comment by chrisjaure** [comment]
In my limited testing, just switching from `ws` to `wss` got rid of the browser error, but I'm not sure if anything else was broken.

Might help to describe my particular problem. I'm trying to get livereactload working in a c9.io environment. The preview defaults to https. Livereload appears to be working in this example: https://github.com/cloud9ide/livereload-example. I'm pretty sure there's no TLS or custom certificate involved in that.

But I couldn't get livereactload working due to the `ws` vs `wss` issue.

**Comment by milankinen** [comment]
Ah if that works then I can do the change. `ws://` is not working with `https` anyway soI don't see any harm by implementing the `ws <> wss` selection based on `location.protocol`

**Comment by elsbree** [comment]
The protocol check [here](https://github.com/milankinen/livereactload/blob/master/src/client/startClient.js#L29):
`const protocol = window.location.protocol === "https" ? "wss" : "ws"`

Is missing the colon in the protocol string, it should be `"https:"`. This results in the client using ws instead of wss in https pages.

**Comment by milankinen** [comment]
Nice notice! Will be fixed soon
