### ISSUE TITLE
Support patching non-React Component classes?

### ISSUE THREAD

**Issue by duncanmak** [milankinen/livereactload#50]
Hello,

I noticed that if I save objects using LrAPI's `setState` and then get them back on reload, methods that were changed do not get patched onto the existing objects.

For example;

```javascript
class Foo {
     constructor(name) { this.name = name; }
     toString() { return this.name; }
}

let instances = [new Foo('a'), new Foo('b'), new Foo('c')];
instances.map(i => i.toString()); // ['a', 'b', 'c']

lrApi.setState(instances);
// patch toString to return this.name.toUppercase() which will trigger reload

// expect ['A', 'B', 'C'], but I get ['a', 'b', 'c'] instead
lrApi.getState().map(i => i()); 

new Foo('d').toString() // 'D', as expected
```

If this is not supported, I'd love to contribute to the project so that this could work, I just need some pointers.

**Comment by milankinen** [comment]
Unfortunately `setState` and `getState` from `livereactload-api` is meant for plain data only. 

What is your goal you are trying to solve with `lrApi.setState`? Perhaps there is a better way to solve it.

**Comment by duncanmak** [comment]
I was inspired by the React Hot Loader talk at ReactEurope, so I set out to recreate what I saw using a different stack (browserify + livereactload + rxjs (instead of redux))

I have it basically working here - https://github.com/duncanmak/experiments/tree/action-playback/flux-by-rx

The main file that loads in the state is here - https://github.com/duncanmak/experiments/blob/action-playback/flux-by-rx/src/main.ts

I tried webpack and HMR and I also can't get it to do this same thing, perhaps I'll need to replace my Event objects with something simpler, alas :disappointed:

**Comment by milankinen** [comment]
Ahh! Then you should definitely take look at ffux: https://github.com/milankinen/ffux

I'm also an enthusiastic FRP user so I implemented ffux especially React+FRP combo in my mind. Live reloading is also supported. Though the examples contain only Webpack version, the same code should work with LiveReactload too (and no lrApi should be needed at all!).
