### ISSUE TITLE
Rewrites JS to DOM multiple times

### ISSUE THREAD

**Issue by zrosenbauer** [milankinen/livereactload#53]
It's way past my bed time at this point....so maybe some sleep would help me resolve this but I seem to be having issues with Babelify + BrowserSync + React-Router + LiveReactLoad. (Thanks BTW as this really lets us stick with Browserify)

It works fine on the first, but not on the second and so on same as: [#43](https://github.com/milankinen/livereactload/issues/43)

I am new to LiveReactLoad....and I'm pretty sure it's not a React-Router issue, any help would be VERY appreciated. BTW if I find some time I might try to help with that magic bullet for React-router if I can :)

**Comment by zrosenbauer** [comment]
Updated issue to actual issue after digging through lrload codebase. Will look into resolving with PR or something hopefully :)

**Comment by milankinen** [comment]
Yeah. I'm going to rewrite the live reloading logic by using [react-proxy](https://github.com/gaearon/react-proxy) and I'm going to steal some ideas from [react-patch-server](https://github.com/Kureev/browserify-patch-server) and [browserify-hrm](https://github.com/AgentME/browserify-hmr)

That should be able to handle this issue correctly. :)

**Comment by milankinen** [comment]
Could you check if this problem is still present in the brand new `2.0.0-alpha2` version? https://github.com/milankinen/livereactload/tree/2.x.x

**Comment by zrosenbauer** [comment]
@milankinen When I get a chance I'll pull it down and take a look. We switched to webpack though as we had to roll. Keep it up though as I am still a fan of browserify for my smaller projects!

**Comment by milankinen** [comment]
Can I close this one?
