### ISSUE TITLE
Hot Reloading Not Possible with ES6 class getters.

### ISSUE THREAD

**Issue by justinanastos** [milankinen/livereactload#54]
It appears to me that using ES6 module syntax along with a `get` function causes the loader to fail. I don't know if this is a solvable problem, but it's something I've run into.

Please let me know if there's anything else I can do to illustrate the issue.

Fully (not) working example can be found here: https://github.com/justinanastos/livereactload-es6-class-get-issue

**Comment by gaearon** [comment]
This will be fixed when/if LiveReactload switches to `react-hot-api@0.5.0-alpha-3` (or directly to `react-proxy` which supersedes `react-hot-api`).

**Comment by justinanastos** [comment]
Thank you @gaearon .

**Comment by milankinen** [comment]
`react-hot-api` version updated in `0.7.0`. Does it work now @justinanastos?

**Comment by justinanastos** [comment]
Sorry for not getting back to you yet @milankinen ! I will have this tested out in the morning. Thanks for getting back so quickly.

**Comment by justinanastos** [comment]
This works flawlessly in the demo project I set up to illustrate the issue. I'd mark this as resolved if you are ok with it @milankinen .

Thank you!
