### ISSUE TITLE
Uncaught TypeError: Cannot read property 'writable' of undefined

### ISSUE THREAD

**Issue by scottcorgan** [milankinen/livereactload#55]
Getting the following error: 

```
Uncaught TypeError: Cannot read property 'writable' of undefined
```

from this line of code: https://github.com/milankinen/livereactload/blob/4086632e64358b5d3eb2953becf9a0765351e600/lib/browser/deps/make-exports-hot.js#L39

using this script:

```
watchify --extension=.jsx -v -t [babelify --stage 0] -g livereactload -e app/assets/javascripts/index.js -o lib/assets/javascripts/bundle.js
```

Any ideas?

**Comment by chrisforrette** [comment]
I'm getting the same error. Here's my watch script:

```bash
#!/bin/bash

node_modules/.bin/watchify --debug --verbose -t [ babelify --optional es7.decorators --optional es7.objectRestSpread --optional runtime ] -t reactify -g livereactload --extension=.jsx --extension=.js static/js/app.js -o static/build/js/app.js -dv &
node_modules/.bin/livereactload monitor -n static/build/js/app.js &
wait
```

**Comment by milankinen** [comment]
@chrisforrette Can you set a breakpoint to that code line and tell me what is the values of `m.exports` and `key` when the error occurs?

**Comment by NateJackman** [comment]
I get this when using react redux.

key: "WrappedComponent"
exports: function Connect..

**Comment by milankinen** [comment]
Could you check if this problem is still present in the brand new `2.0.0-alpha2` version? https://github.com/milankinen/livereactload/tree/2.x.x

**Comment by epixhints** [comment]
I have this issue when using `redux-react`s `connect` function.

Upgrading to `2.0.0-alpha*` gets rid of the exception, the reload runs but it does not do anything to the dom.

```LiveReactload :: WebSocket client listening for changes...
console.js:5 LiveReactload :: Bundle changed
console.js:5 LiveReactload :: Apply patch
handleChange.js:39  > Patch module    :: /Users/jarneson/development/react-playground/src/app.cjsx
handleChange.js:39  > Patch module    :: /Users/jarneson/development/react-playground/components/redux_app.cjsx
handleChange.js:39  > Patch module    :: /Users/jarneson/development/react-playground/src/routes.cjsx
handleChange.js:39  > Patch module    :: /Users/jarneson/development/react-playground/src/root.cjsx
console.js:5 LiveReactload :: Patching complete```

**Comment by epixhints** [comment]
Here's a minimum test case: https://github.com/epixhints/lrload-test-case/tree/master

**Comment by milankinen** [comment]
Thanks @epixhints, managed to re-produce the problem with your example!

About the `2.0.0-*` reload case, LiveReacload `2.x.x` has started using `react-proxy` (https://github.com/gaearon/react-proxy) and `babel-plugin-react-transform`(https://github.com/gaearon/babel-plugin-react-transform). This means that someone should contribute and implement CoffeeScript (judging from the `.cjsx` extension) transformer equal to `babel-plugin-react-transform` and wrap React components with `react-proxy`. 

Do you want to contribute? :)

**Comment by epixhints** [comment]
Coffeescript support is lacking in other places already, so I will probably just cut over to using babel at this point.

2.0.0-alpha3 seems to work perfectly when using pure js, so this issues is all cleared up for me. Thanks for the guidance!
