### ISSUE TITLE
CSP issue

### ISSUE THREAD

**Issue by moimael** [milankinen/livereactload#57]
Hi, 

I'm using livereactload to develop an app for Firefox OS. Everything works pretty well, except when I want to try it on the emulator which enforce strict CSP.

I get this : 
```
Error: call to Function() blocked by CSP
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src app://fdf9027e-8bff-463d-8b94-343146365fb2").
```

Which seems to be related to this code: 
```
 // Create a proxy constructor with matching name
  var ProxyClass = new Function('getCurrentClass', 'return function ' + (InitialClass.name || 'ProxyClass') + '() {\n      return getCurrentClass().apply(this, arguments);\n    }')(function () {
    return CurrentClass;
  });
```

Would it be possible to remove the use of Function ?

Thanks !

**Comment by milankinen** [comment]
This looks like `react-proxy` issue, I suggest to report this issue there https://github.com/gaearon/react-proxy/issues
