### ISSUE TITLE
how to pass --no-server option with api?

### ISSUE THREAD

**Issue by frost555** [milankinen/livereactload#65]
Hello, i would like to try livereactload.
I'm using browserify with gulp and i have multiple bundles (app.js, vendor.js)
I need to start only one instance of server, with first bundle.

How can i specify "--noserver" option when using node api?
I have tried something like

b.plugin("livereactload", {"no-server": true});

but without success. Please tell me the correct way to pass this option.

**Comment by milankinen** [comment]
Have you tried `b.plugin("livereactload", {server: false})`?

**Comment by milankinen** [comment]
Are you using watchify for each bundle? In that case I'd recommend to use unique ports per bundle so that all bundles get hot-reloading capabilities:

```javascript
// bundle1.js
b.plugin("livereactload", {port: 4470})

// bundle2.js
b.plugin("livereactload", {port: 4471})

// etc....
```

**Comment by frost555** [comment]
Thank you, both advices are very helpful. I managed to get livereactload to work.

**Comment by milankinen** [comment]
:+1:
