### ISSUE TITLE
incompatbile with babel.optional[]=runtime

### ISSUE THREAD

**Issue by marionebl** [milankinen/livereactload#71]
When using the optional babel-runtime transform like this
```js
//.babelrc
{
  "optional": ["runtime"]
}
```

livereactload produces the following code 
```js
(function(modules, entryId$$) {
             "use strict";

var _Object$keys = require("babel-runtime/core-js/object/keys")["default"];

var require = (function () {
  require.__byId = __byId;
  return require;
```

which in turn produces a TypeError:

`Uncaught TypeError: require is not a function`

**Comment by milankinen** [comment]
Thanks! It seems that `babel-runtime` tries to override some of the ES6 features used by livereactload initializer. As you can see from the code, babel is trying to use require but it's not defined yet. 

Perhaps prepending the initialization code after (babel) transformations could solve this issue.

**Comment by milankinen** [comment]
Yesh! I was able to re-produce this with `examples/01-basic-usage`. Fix coming soon.

**Comment by eXtreme** [comment]
Great to hear!

**Comment by marionebl** [comment]
:+1:

**Comment by milankinen** [comment]
Should be fixed in `2.0.5`

**Comment by eXtreme** [comment]
It works now, thanks!

**Comment by marionebl** [comment]
Works for me too, thanks!

**Comment by nvartolomei** [comment]
I have the same problem @2.2.3 using https://github.com/agraboso/redux-api-middleware as dependency of my project.
