### ISSUE TITLE
Custom client or transport

### ISSUE THREAD

**Issue by vweevers** [milankinen/livereactload#74]
I'd like to use a custom client, and for that client to be able to read the options (ie host and port), so it can implement its own message transport instead of (or on top of) websockets. Specifically, to have a background page of a chrome extension listen to a livereactload websocket server, and forward messages to content scripts with `chrome.runtime` messaging. The background page calls `client/startClient`, the content script calls `client/handleChange`. TLDR; hot reloading content scripts.

I got this working, but the default livereactload client that gets browserified with the content
script still tries to connect to the server - it shouldn't.

Could be solved in a few different ways:

1. Move [client options](https://github.com/milankinen/livereactload/blob/master/src/browserify-plugin/main.js#L85) to [window.__livereactload$$](https://github.com/milankinen/livereactload/blob/master/src/browserify-plugin/main.js#L38), and add a browserify plugin option to not include client (eg `{ client: false }` or `--no-client`). The `require("livereactload/client", ..)` statement will then be excluded from an entry's source, but a custom client would still be able to read options from `window.__livereactload$$`.
2. Add a browserify plugin option to use a custom client (eg `{ client: 'custom-client' }`). An entry's source will then have `require("custom-client", ..)` instead of `require("livereactload/client", ..)`. Not sure how this plays with the `require()` override.
3. Add a browserify plugin option `startClient`, which will be passed to clientOpts. Then in [client/main.js](https://github.com/milankinen/livereactload/blob/master/src/client/main.js#L5), if `opts.startClient` is false, set `scope$$.options` but don't start client.

**Comment by vweevers** [comment]
I will do a PR, but wanted to discuss this first.

**Comment by milankinen** [comment]
Wow, sounds cool!

The combination of 1 & 2 would be my choice, option precedence could be the following:

1. `--no-client` (or `client: false`) => do not add `require("livereactload/client")` at all
2. `--client=./path/to/customClient` (or `client: "<path>") => 

Add the following require (this should work even with the `requireOverride`) 
```javascript
require("livereactload/client").apply(null, [<clientOpts>, require(<customClientPath>)])
```
And the `livereactload/client` implementation something like
```javascript
 export default function client(opts, customStart) {
  const scope$$ = window.__livereactload$$
  scope$$.options = opts
  if (typeof customStart === "function") {
    customStart(scope$$, opts, handleChange)  // or whatever is the best order of parameters
  } else {
     ... do normal stuff ...
  }
}
```
**Otherwise** use the current implementation 

I apologize that the tests are not the easiest one. For this PR it's ok that existing tests pass. I can manually check that the new configurations work when I'm reviewing the PR.

**Comment by milankinen** [comment]
Btw, is there any need for custom client opts, something like?

    --client-opt-custom1=foo
    --client-opt-custom2=bar

**Comment by vweevers** [comment]
Wouldn't it be preferable to have the same function signature for startClient and a custom one? Eg `customStart(scope$$, onMsg)`. That would suit my purposes, at least.

About client opts, I don't have a need for them yet, but if someone does, I would suggest [subarg](https://www.npmjs.com/package/subarg) syntax: `--client [ customClientPath -beep 3 ]`.

**Comment by vweevers** [comment]
`livereactload/client` would be:

```js
export default function client(opts, customStart) {
  const start = customStart || startClient
  const scope$$ = window.__livereactload$$
  scope$$.options = opts
  start(scope$$, {
    change(msg) {
      info("Bundle changed")
      handleChange(scope$$, msg.data)
    },
    patch(msg) {
    }
  })
}
```

**Comment by milankinen** [comment]
Implemented in `2.1.0`. Thanks @vweevers!

**Comment by vweevers** [comment]
Awesome, thanks for the quick merge!

**Comment by milankinen** [comment]
Can we close this issue?

**Comment by vweevers** [comment]
@milankinen Here's a treat for you :santa:

![livereactload-chrome](https://cloud.githubusercontent.com/assets/3055345/10854838/a30a2524-7f3e-11e5-964c-beb1f5092eba.gif)

**Comment by milankinen** [comment]
Ahh, beautiful! :+1:
