### ISSUE TITLE
Update Depdencies?

### ISSUE THREAD

**Issue by four43** [milankinen/livereactload#77]
I ran tried to run the basic example by installing each dependency myself, just using `npm install --save` etc. nothing fancy. When I tried to run it, I was greeted with some errors as things didn't line up. I don't know enough about this project to fix it, but somethings seemed to have changed their interfaces a bit. This is just a low priority heads up. Thanks :)

**Comment by Polyrhythm** [comment]
Perhaps you mean this? https://github.com/milankinen/livereactload/issues/78

**Comment by four43** [comment]
@Polyrhythm that certainly isn't helping lol. I'm assuming that is related, thanks for the find.

**Comment by milankinen** [comment]
Fix coming tomorrow

**Comment by four43** [comment]
Thanks @matti. I appreciate the work.

On Saturday, November 7, 2015, Matti Lankinen <notifications@github.com>
wrote:

> Fix coming tomorrow
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/milankinen/livereactload/issues/77#issuecomment-154771456>
> .
>


-- 
-Seth

**Comment by milankinen** [comment]
Hmm. It seems this is a bit more complicated because in addition to plugin registration API, babel has also changed its code generation / type builders API which is heavily used by `babel-plugin-transform-react`. 

This will require some major changes to `babel-plugin-transform-react` which may take some time... I'm sorry. :-/

**Comment by four43** [comment]
Far enough, thanks for taking a look.

**Comment by milankinen** [comment]
Babel 6.x finally supported! See https://github.com/milankinen/livereactload#installation or examples

**Comment by four43** [comment]
Nice job! Thanks!
