### ISSUE TITLE
Babel 6 breaks .babelrc setup

### ISSUE THREAD

**Issue by Polyrhythm** [milankinen/livereactload#78]
Title says it all. Plugins are handled differently now. The README for this repo should probably reflect that.

See https://github.com/gaearon/babel-plugin-react-transform/issues/46

**Comment by jedrichards** [comment]
babel-plugin-react-transform has just been updated to support Babel 6 https://github.com/gaearon/babel-plugin-react-transform/pull/50#issuecomment-163110712

**Comment by milankinen** [comment]
Check! See https://github.com/milankinen/livereactload#installation or examples

**Comment by jedrichards** [comment]
:bow:
