### ISSUE TITLE
Unknown option error

### ISSUE THREAD

**Issue by pyryjook** [milankinen/livereactload#82]
I'm using livereactload with gulp. I took the example from your examples -folder. I get this error. Any ideas what could cause this? Has it got something to do with deprecated format in .babelrc -file?  
```
Browserify Error { [ReferenceError: [BABEL] /Users/me/my-project/assets/front/js/___livereactload_entry.js: Unknown option: /Users/me/my-project/.babelrc.env.development.extra while parsing file: /Users/me/my-project/assets/front/js/___livereactload_entry.js]
```

I have three actual bundles, the error is thrown on all of those plus on the file shown in error message above.

**Comment by milankinen** [comment]
Hi @pyryjook! What babel version are you using? Currently LiveReactload is not compatible with `babel@6.x.x` because `babel-plugin-react-transform` doesn't support it yet (see #77).

**Comment by milankinen** [comment]
Babel 6.x finally supported! See https://github.com/milankinen/livereactload#installation or examples

**Comment by milankinen** [comment]
Can I close this issue?

**Comment by pyryjook** [comment]
ah, sorry for my delayed answer. Yes, this can be closed since babel 6 is
now supported. Haven't tried it yet, but most likely that support fixes the
problem I had.
