### ISSUE TITLE
React 0.14.2 ?

### ISSUE THREAD

**Issue by cidevant** [milankinen/livereactload#83]
Hi there, man!

I am trying to migrate my project Tabula Rasa (https://github.com/cidevant/tabula-rasa-build-system) to React 0.14.2 and I have following error:

```
LiveReactload :: Connect reload client to ws://localhost:4474
localhost/:10 Uncaught TypeError: getNative is not a function
(program):10 LiveReactload :: WebSocket client listening for changes...
```
I think this is LODASH problem. I will try to copy whole lodash project from ```node_modules``` to ```src/scripts``` , maybe it will work.

Cant debug this error more, coz console alerts me, that error is produced by 'localhost' (I see this for the first time, before it was script (script path) or VM).

**Comment by cidevant** [comment]
After starting including ```lodash``` from local - error persists, but babel starts alerts something like this:
```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/katz/Code/JavaScript/react-builders/tabula-rasa-build-system/src/scripts/lodash/index.js" as it exceeds the max of "100KB".
```

Tryed to use this hack https://github.com/babel/babelify/issues/62

```
options: {
    transform: [['babelify', { compact: false }]]
}
```
BABEL alert is missing now, but ```getNative``` error persists. Any ideas? 

### Check my project for further debugging.
* Lodash included locally in file ```src/scripts/components/homepage_components``` https://github.com/cidevant/tabula-rasa-build-system/blob/master/src/scripts/components/homepage_components.js
* To use ```compact: true``` mode just comment line 30 and uncomment line 31 in file ```gulpfile.js```
https://github.com/cidevant/tabula-rasa-build-system/blob/master/gulpfile.js

**Comment by milankinen** [comment]
Hi @cidevant! 

It seems that you have `fullPaths: true` in your Browserify config (`gulpfile.js`). LiveReactload has a bug with `fullPaths: true` which is not fixed yet (see  #80). If you turn the config option to `false`, the error should disappear.

**Comment by cidevant** [comment]
No, fullPaths are set to false. It's defined by isProd variable, which is true only when building project.

**Comment by milankinen** [comment]
Please see the `not` operator: https://github.com/cidevant/tabula-rasa-build-system/blob/master/gulpfile.js#L38 :-)

**Comment by milankinen** [comment]
Closing this one if no comments anymore?

**Comment by aflanagan** [comment]
@milankinen - i just set up livereactload yesterday. It's been working great, but I just added [react-bootstrap](http://react-bootstrap.github.io/) as a dependency and started getting this error. Any thoughts on why that might be?

**Comment by milankinen** [comment]
Hi @aflanagan! Do you have any OS example project causing the error?

**Comment by aflanagan** [comment]
Dang, I wish I did. This is in a pretty big company project. I'll see if I can put together a small example.
