### ISSUE TITLE
How would I go about running this with sass?

### ISSUE THREAD

**Issue by EwanValentine** [milankinen/livereactload#84]
Hi there!

Great library. I was just wondering how I'd get this working with sass also? I noticed you had this working with less in your demo video. 

I'm running with `$ node_modules/.bin/watchify ./src/js/app.js -t babelify -p livereactload -o ./dst/app.js`, I have a sass folder in `./src/sass`. 

Cheers,

Ewan

**Comment by milankinen** [comment]
Hi @EwanValentine! LESS live reloading is not part of LiveReactload. In the demovideo I used normal lessc compiler with `watch-run` and `livereaload`.

See more details here: https://github.com/milankinen/node-quickstart/blob/master/package.json#L20-L21

**Comment by EwanValentine** [comment]
Apologise, late response. I took your advice, works like a charm! Thank you! :D
