### ISSUE TITLE
Cannot require _process

### ISSUE THREAD

**Issue by SystemParadox** [milankinen/livereactload#87]
Similar to #49, I am getting the following error with livereactload 2.1.0:

```
Uncaught Error: Module not found: 
```

The unhelpful error is because `name` is used out of scope in `lib/requireOverride.js` line 41. `__byId` has no `name` property.

It's actually failing to `require('_process')`.

Any ideas why this might be, or where I should look to debug this?

Thanks.

**Comment by SystemParadox** [comment]
This seems to be caused by the browserify option `insertGlobals: true`.

**Comment by milankinen** [comment]
Yeah, that is definitely a bug. Must investigate this more after Christmas.

**Comment by milankinen** [comment]
Fixed in version `2.2.0`
