### ISSUE TITLE
Typescript Example

### ISSUE THREAD

**Issue by Haemoglobin** [milankinen/livereactload#89]
Hi - looks like a great library.  

Is it possible to add an example for how to use this successfully with typescript tsx files as the original source input? I tried adding tsify into the browserify plugins as well as livereactload but none of my transpiled typescript seems to end up in the bundled output with both plugins in action (I only get some boilerplate hot reload code in there but nothing else).  

Thanks, 
Hamish

**Comment by milankinen** [comment]
Thanks @Haemoglobin!

I must admit that I didn't quite get what you're actually trying to do. Do you have any public repository containing the codes you've tried so far? 

At the moment LiveReactload uses "standard" `react-proxy` & `babel-plugin-react-transform` stack for HMR so I'm a little bit worried that hot reloading with TypeScript might not be possible atm.. :-/

**Comment by Haemoglobin** [comment]
Sorry I don't have a public repo for this (was at work so can't get it out) - for now I have got it working with webpack. Thanks!
