### ISSUE TITLE
Gulp process does not exit when running tasks.

### ISSUE THREAD

**Issue by vmasto** [milankinen/livereactload#90]
I've followed the gulp example you've provided in this repo. There's something holding on to the Gulp process after it loads the gulpfile, meaning that whenever you run a task (any task) gulp does not exit and requires manual exit with `ctrl` + `c` (twice).

I've pinpointed it to the livereactload module itself.

```js
var bundler = browserify({
  entries:      [ "./site.js" ],
  transform:    [ [babelify, {}], [envify, {}] ],
  plugin:       isProd ? [] : [ lrload ],    // no additional configuration is needed
  debug:        !isProd,
  cache:        {},
  packageCache: {},
  fullPaths:    !isProd                       // for watchify
})
```

Leaving the `plugin` prop empty reverts everything back to normal (gulp tasks exit properly).

Is this expected behaviour? Is there a workaround?

**Comment by milankinen** [comment]
Ahh, nice notice.

I think this might be caused by LiveReactload server that is started when browserify is executed. Does this happen if you try to execute a task that does not use or depend on browserify at all? 

Hmmm, of course you could initialize the plugin with `[lrload, {server: false}]` but it practically disable the live reloading. Could it be possible to see your gulpfile and its tasks so that we could figure out a way to solve this?

**Comment by vmasto** [comment]
As long as the piece of code I posted is even present in the gulpfile this happens with every task, regardless of whether it's using browserify.

For example, this very simple version also suffers from the issue:

```javascript
const bundler = browserify({
	entries: ['./src/main.js'],
	transform: [[babelify, { presets: ['es2015', 'stage-2', 'react'] }]],
	plugin: [lrload],
	debug: true,
	cache: {},
	packageCache: {},
	fullPaths: false
});

gulp.task('css', () => {
	return gulp.src('./src/styles/main.scss')
		.pipe(sass())
		.pipe(gulp.dest('./public/styles'))
});
```

If I run `gulp css`, it will not exit after completion of the task. If I comment out the `plugin: [lrload]` line it exits normally. I've tested a lot with even just a console log task and it's always the same.

**Comment by milankinen** [comment]
Ok, then this is caused by bound `reset` hooks (https://github.com/milankinen/livereactload/blob/master/src/browserify-plugin/main.js#L26)

However, I managed to reproduce this with the example `gulpfile.js`. What do think if the bundler is created with function instead of eagerly creating it every time when gulp is run?

I modified the example's gulpfile and managed to get rid of this issue:
```javascript
"use strict";

var gulp       = require("gulp"),
    gutil      = require("gulp-util"),
    nodemon    = require("gulp-nodemon"),
    source     = require("vinyl-source-stream"),
    buffer     = require("vinyl-buffer"),
    browserify = require("browserify"),
    watchify   = require("watchify"),
    babelify   = require("babelify"),
    envify     = require("envify"),
    lrload     = require("livereactload")


var isProd = process.env.NODE_ENV === "production"


function createBundler(useWatchify) {
  return browserify({
    entries:      [ "./site.js" ],
    transform:    [ [babelify, {}], [envify, {}] ],
    plugin:       isProd || !useWatchify ? [] : [ lrload ],    // no additional configuration is needed
    debug:        !isProd,
    cache:        {},
    packageCache: {},
    fullPaths:    !isProd                       // for watchify
  })
}

gulp.task("bundle:js", function() {
  var bundler = createBundler(false)
  bundler
    .bundle()
    .pipe(source("bundle.js"))
    .pipe(gulp.dest("."))
})

gulp.task("foo", function() {

})

gulp.task("watch:js", function() {
  // start JS file watching and rebundling with watchify
  var bundler = createBundler(true)
  var watcher = watchify(bundler)
  rebundle()
  return watcher
    .on("error", gutil.log)
    .on("update", rebundle)

  function rebundle() {
    gutil.log("Update JavaScript bundle")
    watcher
      .bundle()
      .on("error", gutil.log)
      .pipe(source("bundle.js"))
      .pipe(buffer())
      .pipe(gulp.dest("."))
  }
})

gulp.task("watch:server", function() {
  nodemon({ script: "server.js", ext: "js", ignore: ["gulpfile.js", "bundle.js", "node_modules/*"] })
    .on("change", [])
    .on("restart", function () {
      console.log("Server restarted")
    })
})

gulp.task("default", ["watch:server", "watch:js"])
```

What do you think?

**Comment by milankinen** [comment]
Updated to master
