### ISSUE TITLE
browserify -r <file>:<name> not working

### ISSUE THREAD

**Issue by steveaft** [milankinen/livereactload#92]
I need to call something in my bundle on the including html page.
I've been using the browserify -r flag to include it as "boot"

So I would do something like: 
browserify ... -e $(BOOT)/index.js -r $(BOOT)/index.js:boot ...
(I added the -e for your plugin, which is specifically looking for a -e item)
It looks like my startup module is not being exposed. I get 
Uncaught Error: Cannot find module 'boot'
In the browser.

I'm still digging in to figure this out. Do you have an example of how to expose the entry module to the including page?

Here is a pseudo code fragment of my index.html:
```<body>
    <script src="bundle.js"></script>
    <script>
        require('boot')()
    </script>
```

**Comment by milankinen** [comment]
I'm not sure if I understood the problem correctly. So you want to have two bundles? If I understood `-r` flag correctly, it makes possible to include modules from *other bundles into your bundle* not vice versa. 

Perhaps you want to try `--standalone` flag (though not sure if it works with LiveReactload either.. :smile:)?

**Comment by milankinen** [comment]
Is this question still valid?

**Comment by steveaft** [comment]
I haven't gotten back to this -- I'd say close it, I'll come back if I look into it again, thanks
