### ISSUE TITLE
Notify client about SyntaxError in bundle

### ISSUE THREAD

**Issue by fantua** [milankinen/livereactload#94]
Show this error in client:

SyntaxError: /Users/ibook/Projects/My/react/src/main.jsx: Unexpected token (10:9) while parsing file: /Users/ibook/Projects/My/react/src/main.jsx

**Comment by milankinen** [comment]
Would `console.error` be enough?

**Comment by fantua** [comment]
Of course :+1:

**Comment by milankinen** [comment]
Released in version `2.2.0`
